### ISSUE TITLE
Need docs to identify where to put in you web service the link for node-red.

### ISSUE THREAD

**Issue by JZacharie** [ncarlier/nunux-keeper#10]
Hi,

I can't find in your hosted nunuxkeeper webservice the way to enable the call back for node-red.
https://myip/keeper-credentials/auth/callback

could you please provide some explaination or a link to a docs ?

Thanks in advance
Joseph

**Comment by ncarlier** [comment]
Hi Joseph,
The client registration is not yet exposed by the Web app. However everything is in place to allow that. The API authentication relies on OpenID Connect and is implemented, onto the hosted solution, by Keycloak. Keycloak allows anonymous client registration: http://www.keycloak.org/docs/3.3/securing_apps/topics/client-registration.html
Basically you have to post a registration request like this:

```
curl -X POST \
    -d ' {"redirectUris":["https://<YOUR_IP_OR_FQDN>/*"],"webOrigins":["+"]}' \
    -H "Content-Type:application/json" \
    https://login.nunux.org/auth/realms/nunux.org/clients-registrations/default
```
Replace `<YOUR_IP_OR_FQDN>` by your IP or your domain name.

The response payload will contain the `clientId` and the `secret`.
Note that the response payload also contains a `registrationAccessToken`. This token is important if you want to update or delete this client.

I definitely have to add a feature into Nunux Keeper to make this more user friendly.

Regards.

PS: this GitHub Repository is the old one, Please can you submit other issues on the new one: https://github.com/nunux-keeper

**Comment by ncarlier** [comment]
FYI, you have now the ability to configure API client using OpenID connect flow into the settings of the webapp: https://app.nunux.org/keeper/settings/api-clients
