### ISSUE TITLE
Registration Email Process Not Working

### ISSUE THREAD

**Issue by DaveN21** [ncarlier/nunux-keeper#11]
Hi Nicolas,
Just wondering if there are any problems with registration at this link as it doesn't send a email as a new member at all. I would like to be able to login etc. 

https://login.nunux.org/auth/realms/nunux-keeper/protocol/openid-connect/auth?client_id=nunux-keeper-app&redirect_uri=https%3A%2F%2Fapp.nunux.org%2Fkeeper%2Fdocuments&state=db761f0f-778f-42bc-895a-4ef4bb64dd0c&nonce=b85b98b4-bf96-4efb-9be5-f9389ce0ec88&response_mode=fragment&response_type=code&scope=opened

It's not sending the confirmation email here:
https://login.nunux.org/auth/realms/nunux-keeper/login-actions/required-action?execution=VERIFY_EMAIL&client_id=nunux-keeper-app 

Many thanks,
Dave

**Comment by ncarlier** [comment]
Hello Dave,

thank you very much for your report, my SMTP relay was misconfigured. Everything should be ok now.

Thanks again.

Nicolas

**Comment by DaveN21** [comment]
Hi Nicolas,

Thank you for getting back to me and all good now I can login.

Wondering...the bookmarklet doesn't do what a traditional bookmarklet does when you click it, not sure if I'm missing something. 

Also, would this be able to be used on a social member website for multiple members to use together...just wondering and if you know how would be great?

Thanks for being so available it is amazing.

Much thanks to you,
Dave :-)

**Comment by ncarlier** [comment]
Hi dave,

The bookmarklet is slightly more complex than a simple URL bookmarker. 
When clicked, a small box should appear at the bottom left of the page. You can click on it to send the whole page or you can select with the mouse anything on the page and drag and drop it onto the small box. Then you can click to send the selected content to Nunux Keeper. BTW it's a convenient way to save a page that have some trouble to be correctly extracted.

If you want a simple bookmarklet you can make one using the creation URL. Something like that:

```js
var loc = document.location;
document.location='https://app.nunux.org/keeper/documents/create?url=' + encodeURIComponent(loc);
```

You can use this tool to create your BM: https://mrcoles.com/bookmarklet/

For your last question, Nunux Keeper is a bit poor regarding social feature. For the moment you can only share a label (and all its documents) to anybody (inside or outside of Nunux Keeper).
I planned to add some publish/subscribe mechanism. But I have no ETA about this.

Regards,

Nicolas

**Comment by DaveN21** [comment]
Hi Nicolas,


Thank you for all your help with this. I'll see what we can make of it all and really appreciate your help with everything.


Best regards,

David


________________________________
