### ISSUE TITLE
unsafe cannot be recognized with bookmarklet

### ISSUE THREAD

**Issue by alxlion** [ncarlier/nunux-keeper#2]
Adding a webpage content thanks to the bookmarklet, _Firefox_ doesn't recognize this URL:  

```
unsafe:javascript:%28function%28%29{K_REALM='http://keeper.nunux.org';K_SCR=document.createElement%28'SCRIPT'%29;%20%20%20%20%20%20K_SCR.type='text/javascript';K_SCR.src=K_REALM+'/bookmarklet.js';%20%20%20%20%20%20document.getElementsByTagName%28'head'%29[0].appendChild%28K_SCR%29}%29%28%29;
```

**Unsafe** protocol isn't linked to another software.

**Comment by ncarlier** [comment]
The drop event default behavior was not stopped correctly. See https://github.com/ncarlier/nunux-keeper/commit/ef5c88ca88d60d839844335d49c1455219bc5a8d

Thanks for the report.

**Comment by ncarlier** [comment]
The unsafe prefix was put by Angular compile provider. See https://github.com/ncarlier/nunux-keeper/commit/3f3529c843243b8354c87944897103421c57077b

Thanks for the repport
