### ISSUE TITLE
a web page that do not work

### ISSUE THREAD

**Issue by Cyrille37** [ncarlier/nunux-keeper#3]
Hi, and thanks for this really nice tool.

This page does not work with Keeper : https://www.documentcloud.org/home

Cheers
Cyrille, de Tours ;-)

**Comment by ncarlier** [comment]
Hi, you are welcome :)

this page does not work well because the content algorithm is unable to figure out where is the content. The structure of this page is too complex. However, you can still save this content thanks to the bookmarklet. See issue #4 to see how to proceed.

Thx

**Comment by Cyrille37** [comment]
What's a pity for a Document Cloud service to not have well formed content ...
Thanks for you answer.
