### ISSUE TITLE
Unable to create document: 500 Internal Server Error

### ISSUE THREAD

**Issue by Cyrille37** [ncarlier/nunux-keeper#8]
while trying the "Keep This!" on page http://www.smashingmagazine.com/2015/10/rail-user-centric-model-performance/ it fail with javascript errors visible in this screenshot.

![selection_002](https://cloud.githubusercontent.com/assets/368965/10263345/9677da26-69eb-11e5-8a96-466cc5747164.png)

Cheers

**Comment by ncarlier** [comment]
Hello, 
The website returns gzip content without considering the "Accept-Encoding" header of the request. So to deal with this kind of website I have to check the "Content-Encoding" header of the response to verify if the content is compressed or not.

Thanks for the report.

**Comment by ncarlier** [comment]
Fixed a4916fa
